name: Build macOS .app file

on:
  push:
    branches:
      - main  # Runs on push to main branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest #macos-latest  # Use ''windows-latest' for windows runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Fetch latest code

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Adjust to your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install dependencies

      - name: Install PyInstaller
        run: pip install pyinstaller  # Required for building .app

      - name: Build the .app file
        run: pyinstaller --onefile --name "MyWindowsApp" app.py #pyinstaller --onefile --windowed --name "MyMacApp" app.py #'run: pyinstaller --onefile --name "MyWindowsApp" app.py'

      - name: Upload the .app artifact
        uses: actions/upload-artifact@v4  # Updated version
        with:
          name: windows-exe #macos-app #" windows-exe"
          path: dist/MyMacApp.exe #.exe for windows # Make sure this path is correct



        


