name: Build Windows .exe file

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Use Windows runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build the .exe file
        run: pyinstaller --onefile --name "MyWindowsApp" app.py

      - name: Upload the .exe artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-exe
          path: dist/MyWindowsApp.exe
